---
version: "3.3"

services:

  # -------------------------------------------------------------------------- #
  # ORY KRATOS
  # User database, self-login infrastructure, 2FA authentication
  # https://www.ory.sh/kratos/
  # https://github.com/ory/kratos
  # -------------------------------------------------------------------------- #

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.5.0-alpha.1
    ports:
      - "4455:4455"
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
    restart: on-failure

  kratos:
    image: "oryd/kratos:v0.5.5-alpha.1"
    ports:
      - "4433:4433"
      - "4434:4434"
    environment:
      DSN: "postgres://kratos:secret@kratos_db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4"
    depends_on:
      - kratos_db
      - kratos_migrate
      - mailslurper
    command: serve -c /etc/config/kratos/kratos.yml --dev
    restart: on-failure
    volumes:
      -
        type: bind
        source: ./etc/kratos
        target: /etc/config/kratos

  kratos_migrate:
    image: "oryd/kratos:v0.5.5-alpha.1"
    environment:
      DSN: "postgres://kratos:secret@kratos_db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4"
    depends_on:
      - kratos_db
    command: migrate sql -e --yes
    restart: on-failure
    volumes:
      -
        type: bind
        source: ./etc/kratos
        target: /etc/config/kratos

  kratos_db:
    image: "postgres:12"
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "kratos"
      POSTGRES_DB: "kratos"

  # -------------------------------------------------------------------------- #
  # ORY KETO
  # User and Policies management, a.k.a. the permission mapping users to
  # characters
  # https://www.ory.sh/keto/
  # https://github.com/ory/keto
  # -------------------------------------------------------------------------- #

  keto:
    image: "oryd/keto"
    ports:
      - "4466:4466"
    environment:
      DSN: "postgres://keto:secret@keto_db:5432/keto?sslmode=disable"
    depends_on:
      - keto_db
      - keto_migrate
    restart: on-failure

  keto_migrate:
    image: "oryd/keto"
    environment:
      DSN: "postgres://keto:secret@keto_db:5432/keto?sslmode=disable"
    depends_on:
      - keto_db
    command: migrate sql -e
    restart: on-failure

  keto_db:
    image: "postgres:12"
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "keto"
      POSTGRES_DB: "keto"

  # -------------------------------------------------------------------------- #
  # ORY mailslurper
  # Intercept confirmation emails to ease the testing process.
  # -------------------------------------------------------------------------- #

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    restart: on-failure
