version: "3.3"

services:

  #---------------------------------------------------------------------------#
  # HAPROXY
  # Reverse proxy to secure the gRPC services
  #---------------------------------------------------------------------------#

  hege_proxy:
    image: "jfsmig/hegemonie-demo-haproxy"
    ports: 
      - "8443:8443"
    restart: on-failure

  #---------------------------------------------------------------------------#
  # PROMETHEUS
  # Collection of in-iame timeseries to report the usage of regions
  #---------------------------------------------------------------------------#

  hege_prometheus:
    image: "jfsmig/hegemonie-demo-prometheus:latest"
    ports:
      - "9090:9090"
    restart: on-failure

  #---------------------------------------------------------------------------#
  # HEGEMONIE
  # core services running game instances
  # https://www.hegemonie.be/
  # https://github.com/jfsmig/hegemonie
  #---------------------------------------------------------------------------#

  hege_regions:
    image: "jfsmig/hegemonie-demo"
    expose:
      - "6000"
      - "6001"
    volumes:
      - "/tmp/regions:/data/regions"
    command: server -v regions /data/regions

  hege_events:
    image: "jfsmig/hegemonie-demo"
    expose:
      - "6000"
      - "6001"
    volumes:
      - "/tmp/events:/data/events"
    command: server -v events /data/events

  hege_maps:
    image: "jfsmig/hegemonie-demo"
    expose:
      - "6000"
      - "6001"
    command: server -v maps

