// Copyright (c) 2018-2021 Contributors as noted in the AUTHORS file
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: map.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ListMapsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Marker string `protobuf:"bytes,1,opt,name=marker,proto3" json:"marker,omitempty"`
}

func (x *ListMapsReq) Reset() {
	*x = ListMapsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMapsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMapsReq) ProtoMessage() {}

func (x *ListMapsReq) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMapsReq.ProtoReflect.Descriptor instead.
func (*ListMapsReq) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{0}
}

func (x *ListMapsReq) GetMarker() string {
	if x != nil {
		return x.Marker
	}
	return ""
}

type MapName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CountCities   uint32 `protobuf:"varint,2,opt,name=countCities,proto3" json:"countCities,omitempty"`
	CountVertices uint32 `protobuf:"varint,3,opt,name=countVertices,proto3" json:"countVertices,omitempty"`
	CountEdges    uint32 `protobuf:"varint,4,opt,name=countEdges,proto3" json:"countEdges,omitempty"`
}

func (x *MapName) Reset() {
	*x = MapName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapName) ProtoMessage() {}

func (x *MapName) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapName.ProtoReflect.Descriptor instead.
func (*MapName) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{1}
}

func (x *MapName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapName) GetCountCities() uint32 {
	if x != nil {
		return x.CountCities
	}
	return 0
}

func (x *MapName) GetCountVertices() uint32 {
	if x != nil {
		return x.CountVertices
	}
	return 0
}

func (x *MapName) GetCountEdges() uint32 {
	if x != nil {
		return x.CountEdges
	}
	return 0
}

type ListVerticesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique name of the map
	MapName string `protobuf:"bytes,1,opt,name=mapName,proto3" json:"mapName,omitempty"`
	// Largest integer that is smaller than the expected value of the first
	// vertex ID returned. In other words, the subsequent assertion
	// `reply.items[0] > marker` is true as long as there are items returned.
	Marker uint64 `protobuf:"varint,2,opt,name=marker,proto3" json:"marker,omitempty"`
}

func (x *ListVerticesReq) Reset() {
	*x = ListVerticesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVerticesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVerticesReq) ProtoMessage() {}

func (x *ListVerticesReq) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVerticesReq.ProtoReflect.Descriptor instead.
func (*ListVerticesReq) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{2}
}

func (x *ListVerticesReq) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *ListVerticesReq) GetMarker() uint64 {
	if x != nil {
		return x.Marker
	}
	return 0
}

type ListEdgesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique name of the map
	MapName string `protobuf:"bytes,1,opt,name=mapName,proto3" json:"mapName,omitempty"`
	// Largest integer that is smaller than the expected value of the first
	// vertex ID used as a source in the set returned. In other words, the
	// subsequent assertion is true
	// `reply.items[0].Src > markerSrc && reply.items[0].Dst > markerDst`
	MarkerSrc uint64 `protobuf:"varint,2,opt,name=markerSrc,proto3" json:"markerSrc,omitempty"`
	// Largest integer that is smaller than the expected value of the first
	// vertex ID used as a source in the set returned. In other words, the
	// subsequent assertion is true
	// `reply.items[0].Src > markerSrc && reply.items[0].Dst > markerDst`
	MarkerDst uint64 `protobuf:"varint,3,opt,name=markerDst,proto3" json:"markerDst,omitempty"`
}

func (x *ListEdgesReq) Reset() {
	*x = ListEdgesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEdgesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEdgesReq) ProtoMessage() {}

func (x *ListEdgesReq) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEdgesReq.ProtoReflect.Descriptor instead.
func (*ListEdgesReq) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{3}
}

func (x *ListEdgesReq) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *ListEdgesReq) GetMarkerSrc() uint64 {
	if x != nil {
		return x.MarkerSrc
	}
	return 0
}

func (x *ListEdgesReq) GetMarkerDst() uint64 {
	if x != nil {
		return x.MarkerDst
	}
	return 0
}

type ListCitiesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique name of the map
	MapName string `protobuf:"bytes,1,opt,name=mapName,proto3" json:"mapName,omitempty"`
	// Largest integer that is smaller than the expected value of the first
	// vertex ID used as a source in the set returned. In other words, the
	// subsequent assertion is true
	// `reply.items[0].ID > marker`
	Marker uint64 `protobuf:"varint,2,opt,name=marker,proto3" json:"marker,omitempty"`
}

func (x *ListCitiesReq) Reset() {
	*x = ListCitiesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCitiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCitiesReq) ProtoMessage() {}

func (x *ListCitiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCitiesReq.ProtoReflect.Descriptor instead.
func (*ListCitiesReq) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{4}
}

func (x *ListCitiesReq) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *ListCitiesReq) GetMarker() uint64 {
	if x != nil {
		return x.Marker
	}
	return 0
}

type CityLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the cell that must carry the city
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the City after the creation
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CityLocation) Reset() {
	*x = CityLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityLocation) ProtoMessage() {}

func (x *CityLocation) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityLocation.ProtoReflect.Descriptor instead.
func (*CityLocation) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{5}
}

func (x *CityLocation) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CityLocation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Vertex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X  uint64 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y  uint64 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vertex) Reset() {
	*x = Vertex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertex) ProtoMessage() {}

func (x *Vertex) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertex.ProtoReflect.Descriptor instead.
func (*Vertex) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{6}
}

func (x *Vertex) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vertex) GetX() uint64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vertex) GetY() uint64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src uint64 `protobuf:"varint,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst uint64 `protobuf:"varint,2,opt,name=dst,proto3" json:"dst,omitempty"`
}

func (x *Edge) Reset() {
	*x = Edge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{7}
}

func (x *Edge) GetSrc() uint64 {
	if x != nil {
		return x.Src
	}
	return 0
}

func (x *Edge) GetDst() uint64 {
	if x != nil {
		return x.Dst
	}
	return 0
}

type PathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique name of the map
	MapName string `protobuf:"bytes,1,opt,name=mapName,proto3" json:"mapName,omitempty"`
	// Source of the path (Vertex ID)
	Src uint64 `protobuf:"varint,2,opt,name=src,proto3" json:"src,omitempty"`
	// Target of the path (Vertex ID)
	Dst uint64 `protobuf:"varint,3,opt,name=dst,proto3" json:"dst,omitempty"`
	// How many max hops are expected
	Max uint32 `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{8}
}

func (x *PathRequest) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *PathRequest) GetSrc() uint64 {
	if x != nil {
		return x.Src
	}
	return 0
}

func (x *PathRequest) GetDst() uint64 {
	if x != nil {
		return x.Dst
	}
	return 0
}

func (x *PathRequest) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type PathElement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier of the Vertex/City belonging to the path.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PathElement) Reset() {
	*x = PathElement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathElement) ProtoMessage() {}

func (x *PathElement) ProtoReflect() protoreflect.Message {
	mi := &file_map_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathElement.ProtoReflect.Descriptor instead.
func (*PathElement) Descriptor() ([]byte, []int) {
	return file_map_proto_rawDescGZIP(), []int{9}
}

func (x *PathElement) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_map_proto protoreflect.FileDescriptor

var file_map_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68, 0x65, 0x67,
	0x65, 0x2e, 0x6d, 0x61, 0x70, 0x22, 0x25, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x70,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x22, 0x85, 0x01, 0x0a,
	0x07, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x74,
	0x69, 0x63, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45, 0x64, 0x67,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45,
	0x64, 0x67, 0x65, 0x73, 0x22, 0x43, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x74,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x22, 0x64, 0x0a, 0x0c, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x64, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x72, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x72,
	0x63, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x44, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x44, 0x73, 0x74, 0x22,
	0x41, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x22, 0x32, 0x0a, 0x0c, 0x43, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x79, 0x22, 0x2a, 0x0a, 0x04,
	0x45, 0x64, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x64, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x0b, 0x50, 0x61, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x1d, 0x0a, 0x0b, 0x50, 0x61, 0x74, 0x68, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x32, 0xa9, 0x02, 0x0a, 0x03, 0x4d, 0x61, 0x70, 0x12, 0x34,
	0x0a, 0x04, 0x4d, 0x61, 0x70, 0x73, 0x12, 0x15, 0x2e, 0x68, 0x65, 0x67, 0x65, 0x2e, 0x6d, 0x61,
	0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x70, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e,
	0x68, 0x65, 0x67, 0x65, 0x2e, 0x6d, 0x61, 0x70, 0x2e, 0x4d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73,
	0x12, 0x19, 0x2e, 0x68, 0x65, 0x67, 0x65, 0x2e, 0x6d, 0x61, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x68, 0x65,
	0x67, 0x65, 0x2e, 0x6d, 0x61, 0x70, 0x2e, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x33, 0x0a, 0x05, 0x45, 0x64, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x68, 0x65, 0x67,
	0x65, 0x2e, 0x6d, 0x61, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x64, 0x67, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x68, 0x65, 0x67, 0x65, 0x2e, 0x6d, 0x61, 0x70, 0x2e, 0x45, 0x64,
	0x67, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x06, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x12, 0x17, 0x2e, 0x68, 0x65, 0x67, 0x65, 0x2e, 0x6d, 0x61, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x68, 0x65, 0x67, 0x65,
	0x2e, 0x6d, 0x61, 0x70, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x15, 0x2e, 0x68, 0x65, 0x67, 0x65, 0x2e, 0x6d, 0x61, 0x70, 0x2e, 0x50, 0x61, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x68, 0x65, 0x67, 0x65, 0x2e, 0x6d,
	0x61, 0x70, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_map_proto_rawDescOnce sync.Once
	file_map_proto_rawDescData = file_map_proto_rawDesc
)

func file_map_proto_rawDescGZIP() []byte {
	file_map_proto_rawDescOnce.Do(func() {
		file_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_map_proto_rawDescData)
	})
	return file_map_proto_rawDescData
}

var file_map_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_map_proto_goTypes = []interface{}{
	(*ListMapsReq)(nil),     // 0: hege.map.ListMapsReq
	(*MapName)(nil),         // 1: hege.map.MapName
	(*ListVerticesReq)(nil), // 2: hege.map.ListVerticesReq
	(*ListEdgesReq)(nil),    // 3: hege.map.ListEdgesReq
	(*ListCitiesReq)(nil),   // 4: hege.map.ListCitiesReq
	(*CityLocation)(nil),    // 5: hege.map.CityLocation
	(*Vertex)(nil),          // 6: hege.map.Vertex
	(*Edge)(nil),            // 7: hege.map.Edge
	(*PathRequest)(nil),     // 8: hege.map.PathRequest
	(*PathElement)(nil),     // 9: hege.map.PathElement
}
var file_map_proto_depIdxs = []int32{
	0, // 0: hege.map.Map.Maps:input_type -> hege.map.ListMapsReq
	2, // 1: hege.map.Map.Vertices:input_type -> hege.map.ListVerticesReq
	3, // 2: hege.map.Map.Edges:input_type -> hege.map.ListEdgesReq
	4, // 3: hege.map.Map.Cities:input_type -> hege.map.ListCitiesReq
	8, // 4: hege.map.Map.GetPath:input_type -> hege.map.PathRequest
	1, // 5: hege.map.Map.Maps:output_type -> hege.map.MapName
	6, // 6: hege.map.Map.Vertices:output_type -> hege.map.Vertex
	7, // 7: hege.map.Map.Edges:output_type -> hege.map.Edge
	5, // 8: hege.map.Map.Cities:output_type -> hege.map.CityLocation
	9, // 9: hege.map.Map.GetPath:output_type -> hege.map.PathElement
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_map_proto_init() }
func file_map_proto_init() {
	if File_map_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMapsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListVerticesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEdgesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCitiesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vertex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Edge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathElement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_map_proto_goTypes,
		DependencyIndexes: file_map_proto_depIdxs,
		MessageInfos:      file_map_proto_msgTypes,
	}.Build()
	File_map_proto = out.File
	file_map_proto_rawDesc = nil
	file_map_proto_goTypes = nil
	file_map_proto_depIdxs = nil
}
