# Check https://circleci.com/docs/2.0/language-go/ for more details
---
version: 2
jobs:
  build:
    docker:
      - image: jfsmig/hegemonie-dependencies:latest
    environment:
      GOPATH: /gopath
      PATH: /gopath/bin:/go/bin:/usr/local/go/bin:/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin
    steps:
      - checkout
      - run: |
          go get -u -t github.com/golang/protobuf
          go get -u -t google.golang.org/grpc
          go get \
            google.golang.org/protobuf/cmd/protoc-gen-go \
            google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - run: |
          make prepare
          go get -v -t -d ./...
          go mod download
      - run: make
      - run: make test
      - run: make benchmark
      - run:
          name: Code Coverage
          command: |
            rm profile.out
            bash <(curl -s https://codecov.io/bash)
          when: on_success
