# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: jfsmig/hegemonie-dependencies:latest
    steps:
      - checkout
      - run: |
          go mod download
      - run: |
          go get -v -t -d ./...
          go get -u -t github.com/golang/protobuf
          go get -u -t google.golang.org/grpc
          go install github.com/golang/protobuf/protoc-gen-go/
      - run: make
      - run: make test
      - run: make benchmark
      - run:
          name: Code Coverage
          command: |
            rm profile.out
            bash <(curl -s https://codecov.io/bash)
          when: on_success
