# Check https://circleci.com/docs/2.0/language-go/ for more details
---
version: 2
jobs:

  sanity:
    parallelism: 1
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends make protobuf-compiler librocksdb-dev librocksdb5.17
      - run: |
          go get -u -t github.com/golang/protobuf@v1.4.3
          go get -u -t google.golang.org/grpc@v1.35.0
          go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.25.0
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0
      - run: |
          set -ex
          make clean
          go mod download
          make prepare
          git diff --exit-code --quiet -- api/ docs/ etc/ pkg/ bin/

  build:
    parallelism: 1
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends librocksdb-dev librocksdb5.17
      - run: |
          set -ex
          go get -v -t -d ./...
          go mod download
          cd pkg/hege
          go install
      - run: |
          ./bin/hege-ci-test coverage.txt
      - run:
          name: Code Coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
          when: on_success

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - sanity

