[Move]
description = "Army movement seen by the local city"
hash = "sha1-834486ef495924fc9e64c0203c3070f077b1c1cc"
one = "{{.SourceCity}}: {{.Army}} passe à procimité."
other = "{{.SourceCity}}: {{.Army}} passe à proximité."
