---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
  - job_name: bundle
    static_configs:
      - targets: ['localhost:6001']
    tls_config:
      insecure_skip_verify: true
